name: HDDL.1

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - setuptools
  - wheel

  - pip:
    - torch==2.9.0
    - torchaudio==2.9.0
    - torchvision==0.24.0
    - torchsummary==1.5.1

    - numpy==2.3.4
    - scikit-learn
    - pandas
    - scipy

    - matplotlib
    - seaborn
    - marimo

    - segmentation-models-pytorch
    - albumentations

    - ipykernel 
    - jupyterlab
    - ipywidgets
